# Generated by Django 3.2.5 on 2021-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_category2_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category2',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category2',
            name='description',
            field=models.TextField(blank=True, default='For match against: '),
        ),
    ]
