# Generated by Django 3.2.5 on 2021-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20210710_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category2',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
