# Generated by Django 3.2.5 on 2021-07-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_category2_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='date',
        ),
    ]
